:sparkles: StreamParsing - Add streaming parsing capacity
ZeroGachis/magicparse pull request #12
Opened 2023-11-02 13:11 UTC by pewho

2023-11-02 16:48 UTC, pewho commented on magicparse/schema.py
> +    def get_stream_readers(self, content: bytes) -> Tuple[Iterable, Iterable]:
J'ai pas trouvé mieux pour avoir le stream en double : en CSV, on ne peux pas acceder à la ligne lue dans le fichier (le reader ne la montre pas).
=> on a le fichier qui est donc en RAM :/

2023-11-03 08:44 UTC, tuxtoby commented on magicparse/__init__.py
> +        on_invalid_parsed_row=on_invalid_parsed_row,
C'est quoi le besoin exact svp? @antoine-b-smartway @pewho @EwenBALOUIN

2023-11-03 10:33 UTC, ducdetronquito commented
Hey @pewho !

C'est quoi le final: pourquoi vous avez besoin de récupérer la ligne en cours avant de la fin

2023-11-03 11:12 UTC, antoine-b-smartway commented on magicparse/schema.py
> +                item[field.key] = value
Effectivement ça serait mieux que parse appelle stream_parse. Mais il devra passer des callbacks pour construire les paramètres de retour.

2023-11-03 11:14 UTC, antoine-b-smartway commented on magicparse/__init__.py
> +        on_invalid_parsed_row=on_invalid_parsed_row,
Le but est d'agréger plusieurs fichiers d'import d'article en un seul. On n'a pas forcément besoin d'avoir la donnée parsée, on veut juste l'ean et la ligne brute originale pour la remettre dans le fichier de sortie.

2023-11-03 11:16 UTC, antoine-b-smartway commented
> Hey @pewho !
> 
> C'est quoi le final: pourquoi vous avez besoin de récupérer la ligne en cours avant de la fin du parsing, sachant qu'in fine tu récupères toutes les lignes parsées correctement et toutes les lignes en erreurs.
> 
> EDIT: Miss click, je ne voulais pas close la PR

Le but est de regénérer un fichier articles agrégeant plusieurs fichiers articles. Donc on veut repousser dans le fichier final la ligne exacte en entrée et non pas s'amuser à resérialiser la donnée (qui varie selon le client).

2023-11-03 11:21 UTC, tuxtoby commented on magicparse/__init__.py
> +        on_invalid_parsed_row=on_invalid_parsed_row,
Et pourquoi vous avez besoin de ça ? (désolé c'est vraiment pour comprendre 😄)

2023-11-03 14:30 UTC, a-bertrand commented on magicparse/__init__.py
> +        on_invalid_parsed_row=on_invalid_parsed_row,
Pour rejouer les X arti d'un mag dans l'ordre.

2023-11-03 14:40 UTC, a-bertrand commented on magicparse/__init__.py
> +        on_invalid_parsed_row=on_invalid_parsed_row,
Pourquoi avoir la version brute ? J'ai peut être raté un truc, mais si au final notre fichier va être "tagué/nommé" d'une manière "spécifique", finalement on sait que pour lui on n'a pas besoin d'appliquer de parser.

2023-11-06 08:12 UTC, pewho commented on magicparse/__init__.py
> +        on_invalid_parsed_row=on_invalid_parsed_row,
c'est l'autre possiblité, mais ça veut dire que l'on fait un parser particulier pour celui ci. Je ne sais pas si c'est ce que l'on veut ?

2023-11-06 08:13 UTC, pewho commented on magicparse/schema.py
> +                item[field.key] = value
ya un autre probleme, c'est que le reader dans stream_parse charge tout, ça me fait mal de pourrir les capacités pour le mode normal (parse), juste pour ne pas C/C

2023-11-06 08:16 UTC, pewho commented
@ducdetronquito En fait on veut les 2 : On a besoin de la ligne Raw, et d'une clef unique (l'ean), donc du parsing
Par contre @antoine-b-smartway,  @a-bertrand a peut etre une bonne idée : on fait un CSV avec un format custom, et une file config particuliere pour l'init, ça me va aussi, et ça ne nous oblige pas a faire des contorsions digne de Majax dans la lib (@ducdetronquito a totalement raison qu'on lui fait un german suplex)

2023-11-06 08:29 UTC, a-bertrand commented on magicparse/__init__.py
> +        on_invalid_parsed_row=on_invalid_parsed_row,
Bas justement pas de parseur

2023-11-06 09:03 UTC, ducdetronquito commented
Dispo pour discuter de cette PR en vocal; je suis vraiment pas convaincu de la solution.

2023-11-06 09:04 UTC, ducdetronquito requested changes
Dispo pour discuter de cette PR en vocal; je suis vraiment pas convaincu de la solution.

2023-11-06 10:41 UTC, closed without merging

2023-11-06 10:42 UTC, pewho commented
Abandoné pour une autre solution :)